import pandas as pd
import matplotlib.pyplot as plt

filename = 'EPC_OPTO_SLEEP_.csv'
df = pd.read_csv(filename)

plt.figure(figsize=(10, 6))
plt.plot(range(len(df.iloc[:, :1])), df["port1_H"], label='Port 1 Power (mW)')
plt.plot(range(len(df.iloc[:, :2])), df["port2_H"], label='Port 2 Power (mW)')
plt.plot(range(len(df.iloc[:, :3])), df["port3_H"], label='Port 3 Power (mW)')
plt.plot(range(len(df.iloc[:, :4])), df["port4_H"], label='Port 4 Power (mW)')
plt.xlabel('Epoch')
plt.ylabel('Relative Power (mW)')
plt.title('Port Power Vs, Epoch H')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(range(len(df.iloc[:, :1])), df["port1_D"], label='Port 1 Power (mW)')
plt.plot(range(len(df.iloc[:, :2])), df["port2_D"], label='Port 2 Power (mW)')
plt.plot(range(len(df.iloc[:, :3])), df["port3_D"], label='Port 3 Power (mW)')
plt.plot(range(len(df.iloc[:, :4])), df["port4_D"], label='Port 4 Power (mW)')
plt.xlabel('Epoch')
plt.ylabel('Relative Power (mW)')
plt.title('Port Power Vs, Epoch D')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(range(len(df["V1"])), df["V1"], label='Port 1 Voltage (mV)')
plt.plot(range(len(df["V2"])), df["V2"], label='Port 2 Voltage (mV)')
plt.plot(range(len(df["V3"])), df["V3"], label='Port 3 Voltage (mV)')
plt.plot(range(len(df["V4"])), df["V4"], label='Port 4 Voltage (mV)')
plt.xlabel('Epoch')
plt.ylabel('Port Voltage ')
plt.title('Port Voltage Vs, Epoch')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))
plt.plot(range(len(df["Cost"])),df["Cost"], label='Cost')
plt.xlabel('Epoch')
plt.ylabel('Cost Value')
plt.title('Cost vs Epoch')
plt.legend()
plt.grid(True)
plt.show()